// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC777/IERC777Recipient.sol";
import "@openzeppelin/contracts/utils/introspection/IERC1820Registry.sol";
import "@openzeppelin/contracts/utils/introspection/ERC1820Implementer.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

interface IStaking {
    function deposit(address to, uint256 amount) external;
}

interface IStakingFactory {
    function predictStakedTokenAddress(address stakeableToken) external view returns (address);
}

/**
 * @title StakingHelper
 * @dev Simple ERC777 token receiver contract
 */
contract StakingHelper is IERC777Recipient, ERC1820Implementer, Ownable {
    IERC1820Registry private _erc1820 = IERC1820Registry(0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24);
    
    // Interface hash for ERC777TokensRecipient
    bytes32 private constant TOKENS_RECIPIENT_INTERFACE_HASH = keccak256("ERC777TokensRecipient");
    
    event TokenNotSupported(address token);

    /**
     * @dev Constructor that registers this contract as an ERC777 token recipient
     */
    constructor(address owner) Ownable(owner) {
        // Register this contract as an implementer of ERC777TokensRecipient
        _erc1820.setInterfaceImplementer(
            address(this),
            TOKENS_RECIPIENT_INTERFACE_HASH,
            address(this)
        );
    }

    mapping(address => address) public stakingContracts;
    
    /**
     * @dev Store the staking contract for a given token
     * @param token The address of the token
     * @param stakingContract The address of the staking contract
     */
    function storePairs(address[] memory tokens, address[] memory stakingContracts) external onlyOwner {
        for (uint i = 0; i < tokens.length; i++) {
            stakingContracts[tokens[i]] = stakingContracts[i];
            // approve the staking contract to spend the token
            IERC20(tokens[i]).approve(stakingContracts[i], type(uint256).max);
        }
    }

    /**
     * @dev Hook called when tokens are sent to this contract
     * @param operator The address which initiated the send (i.e. msg.sender)
     * @param from The address which previously owned the token
     * @param to The address which the tokens are being sent to (should be this contract)
     * @param amount The number of tokens being sent
     * @param userData Data generated by the user to be sent to the recipient
     * @param operatorData Data generated by the operator to be sent to the recipient
     */
    function tokensReceived(
        address operator,
        address from,
        address to,
        uint256 amount,
        bytes calldata userData,
        bytes calldata operatorData
    ) external override {
        // based on the token received, fetch it from the stakingContracts mapping
        // if the token is not in the mapping, return the tokens to the "from" address. This ensures our batches don't fail if one of the tokens is not supported yet
        // if the token is in the mapping, call the deposit function on the staking contract, setting the "from" address as the "to" parameter
        if (stakingContracts[msg.sender] == address(0)) {
            IERC20(msg.sender).transfer(from, amount);
            emit TokenNotSupported(msg.sender);
        } else {
            IStaking(stakingContracts[msg.sender]).deposit(from, amount);
        }
    }
} 